# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.12

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.12.1/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.12.1/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/zhiboluo/deal.ii-candi/deal.II-v9.0.0/examples/thermo-elasto-plastic-mpi-mac-v1

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/zhiboluo/deal.ii-candi/deal.II-v9.0.0/examples/thermo-elasto-plastic-mpi-mac-v1

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.12.1/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.12.1/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/zhiboluo/deal.ii-candi/deal.II-v9.0.0/examples/thermo-elasto-plastic-mpi-mac-v1/CMakeFiles /Users/zhiboluo/deal.ii-candi/deal.II-v9.0.0/examples/thermo-elasto-plastic-mpi-mac-v1/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/zhiboluo/deal.ii-candi/deal.II-v9.0.0/examples/thermo-elasto-plastic-mpi-mac-v1/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named info

# Build rule for target.
info: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 info
.PHONY : info

# fast build rule for target.
info/fast:
	$(MAKE) -f CMakeFiles/info.dir/build.make CMakeFiles/info.dir/build
.PHONY : info/fast

#=============================================================================
# Target rules for targets named strip_comments

# Build rule for target.
strip_comments: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 strip_comments
.PHONY : strip_comments

# fast build rule for target.
strip_comments/fast:
	$(MAKE) -f CMakeFiles/strip_comments.dir/build.make CMakeFiles/strip_comments.dir/build
.PHONY : strip_comments/fast

#=============================================================================
# Target rules for targets named distclean

# Build rule for target.
distclean: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 distclean
.PHONY : distclean

# fast build rule for target.
distclean/fast:
	$(MAKE) -f CMakeFiles/distclean.dir/build.make CMakeFiles/distclean.dir/build
.PHONY : distclean/fast

#=============================================================================
# Target rules for targets named debug

# Build rule for target.
debug: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 debug
.PHONY : debug

# fast build rule for target.
debug/fast:
	$(MAKE) -f CMakeFiles/debug.dir/build.make CMakeFiles/debug.dir/build
.PHONY : debug/fast

#=============================================================================
# Target rules for targets named runclean

# Build rule for target.
runclean: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 runclean
.PHONY : runclean

# fast build rule for target.
runclean/fast:
	$(MAKE) -f CMakeFiles/runclean.dir/build.make CMakeFiles/runclean.dir/build
.PHONY : runclean/fast

#=============================================================================
# Target rules for targets named run

# Build rule for target.
run: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 run
.PHONY : run

# fast build rule for target.
run/fast:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/build
.PHONY : run/fast

#=============================================================================
# Target rules for targets named release

# Build rule for target.
release: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 release
.PHONY : release

# fast build rule for target.
release/fast:
	$(MAKE) -f CMakeFiles/release.dir/build.make CMakeFiles/release.dir/build
.PHONY : release/fast

#=============================================================================
# Target rules for targets named sign

# Build rule for target.
sign: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sign
.PHONY : sign

# fast build rule for target.
sign/fast:
	$(MAKE) -f CMakeFiles/sign.dir/build.make CMakeFiles/sign.dir/build
.PHONY : sign/fast

#=============================================================================
# Target rules for targets named thermo-elasto-plastic

# Build rule for target.
thermo-elasto-plastic: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 thermo-elasto-plastic
.PHONY : thermo-elasto-plastic

# fast build rule for target.
thermo-elasto-plastic/fast:
	$(MAKE) -f CMakeFiles/thermo-elasto-plastic.dir/build.make CMakeFiles/thermo-elasto-plastic.dir/build
.PHONY : thermo-elasto-plastic/fast

thermo-elasto-plastic.o: thermo-elasto-plastic.cc.o

.PHONY : thermo-elasto-plastic.o

# target to build an object file
thermo-elasto-plastic.cc.o:
	$(MAKE) -f CMakeFiles/thermo-elasto-plastic.dir/build.make CMakeFiles/thermo-elasto-plastic.dir/thermo-elasto-plastic.cc.o
.PHONY : thermo-elasto-plastic.cc.o

thermo-elasto-plastic.i: thermo-elasto-plastic.cc.i

.PHONY : thermo-elasto-plastic.i

# target to preprocess a source file
thermo-elasto-plastic.cc.i:
	$(MAKE) -f CMakeFiles/thermo-elasto-plastic.dir/build.make CMakeFiles/thermo-elasto-plastic.dir/thermo-elasto-plastic.cc.i
.PHONY : thermo-elasto-plastic.cc.i

thermo-elasto-plastic.s: thermo-elasto-plastic.cc.s

.PHONY : thermo-elasto-plastic.s

# target to generate assembly for a file
thermo-elasto-plastic.cc.s:
	$(MAKE) -f CMakeFiles/thermo-elasto-plastic.dir/build.make CMakeFiles/thermo-elasto-plastic.dir/thermo-elasto-plastic.cc.s
.PHONY : thermo-elasto-plastic.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... info"
	@echo "... strip_comments"
	@echo "... distclean"
	@echo "... debug"
	@echo "... runclean"
	@echo "... run"
	@echo "... release"
	@echo "... sign"
	@echo "... thermo-elasto-plastic"
	@echo "... thermo-elasto-plastic.o"
	@echo "... thermo-elasto-plastic.i"
	@echo "... thermo-elasto-plastic.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

